#!/usr/bin/with-contenv bash

FLAGS="--stateful-filtering"

# configure `tailscale up`
if ! [ -v TAILSCALE_AUTHKEY ]; then
    echo '[!] TAILSCALE_AUTHKEY is not defined, this will print a login URL to the screen'
else
    FLAGS="${FLAGS} --authkey=${TAILSCALE_AUTHKEY}"
fi

if [ -v TAILSCALE_HOSTNAME ]; then
    FLAGS="${FLAGS} --hostname=${TAILSCALE_HOSTNAME}"
fi

if [ -v TAILSCALE_USE_TAGS ]; then
    FLAGS="$flags --advertise-tags=${TAILSCALE_USE_TAGS}"
fi

if [ -v TAILSCALE_USE_SSH ]; then
    FLAGS="${FLAGS} --ssh=${TAILSCALE_USE_SSH}"
fi

if [ -v TAILSCALE_BE_EXIT_NODE ]; then
    echo '[!] acting as an exit node, you may need to approve this in the admin console'
    FLAGS="${FLAGS} --advertise-exit-node=${TS_BE_EXIT_NODE}"
fi

if [ -v TAILSCALE_LOGIN_SERVER ]; then
    echo '[!] Using a custom login server'
    FLAGS="${FLAGS} --login-server=${TAILSCALE_LOGIN_SERVER}"
fi

tailscale up $FLAGS

# configure serve or funnel, or reset if not set/removed
# serve no longer requires mode specified and natively defaults to https on 443
if [ -v TAILSCALE_SERVE_PORT ] then

    SERVE_FLAGS="--bg"

    if [[ -v TAILSCALE_SERVE_MODE && ${TAILSCALE_SERVE_MODE} == "http"]]; then 
        SERVE_FLAGS="${SERVE_FLAGS} --http=80"
    fi

    if [ -v TAILSCALE_FUNNEL ]; then
        tailscale funnel $SERVE_FLAGS http://localhost:"${TAILSCALE_SERVE_PORT}"
    else
        tailscale funnel reset
        tailscale serve $SERVE_FLAGS http://localhost:"${TAILSCALE_SERVE_PORT}"
    fi

else
    tailscale serve reset
    tailscale funnel reset 
fi




